accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("mypage/<int:pk>/", views.mypage, name="mypage"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("follow/<int:pk>/", views.follow, name="follow"),
    
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:item_pk>/", views.detail, name="detail"),
    path("pick/", views.pick, name="pick"),  # 임시 경로
    path("picking/", views.picking, name="picking"),
    path("pick/delete", views.delete_picked, name="delete_picked"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path("accounts/", include("accounts.urls")),
    path("items/", include("items.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name ='reviews'


urlpatterns = [
    path('', views.index, name='index'),
    # 리뷰작성 
    path('<int:item_id>/create/', views.create, name='create'),
    # 리뷰 상세 조회
    path('<int:pk>/', views.detail, name='detail'),
    # 리뷰 수정
    path('<int:pk>/update/', views.update, name='update'),
    # 리뷰 삭제
    path('<int:pk>/delete/', views.delete, name='delete'),
    # 리뷰 좋아요
    path('<int:pk>/like/', views.like, name='like'),
    # 댓글 작성
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    # 댓글 삭제
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name ='comment_delete'),

]

reviews/models.py
from django.db import models
from django.conf import settings
from items.models import Item
# 이미지
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill

# Datetime
from django.utils import timezone
from datetime import datetime, timedelta


class Review(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    order_at = models.DateField('구매일', null=True)
    image = ProcessedImageField(upload_to='reviews/images/', blank=True,
                            processors=[ResizeToFill(1200, 960)],
                            format='JPEG',
                            options={'quality': 80})
       
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

reviews/forms.py
from django import forms
from .models import Review, Comment
from django.forms.widgets import DateInput, Textarea

class ReviewForm(forms.ModelForm):

    # title => 제목
    title = forms.CharField(
        label ='제목',
        widget=forms.TextInput(attrs={
            'placeholder' : '제목'
        })
    )
    # content => 내용
    content = forms.CharField(
        label ='내용',
        widget=forms.TextInput(attrs={
            'placeholder' : '내용'
        })
    )
    

    class Meta:
        model = Review
        fields = ['title','image', 'content', 'order_at']
        widgets = {
            'order_at': DateInput(attrs={'type': 'date'}),
            'content': Textarea(attrs={'rows':4})
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        widgets = {
            'content': Textarea(attrs={'rows':4})

        }

reviews/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_safe
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Review, Comment
from reviews.forms import ReviewForm, CommentForm
from django.core.paginator import Paginator
from django.db.models import Count
# Create your views here.

def index(request):
    sort = request.GET.get('sort','') #url의 쿼리스트링을 가져온다. 없는 경우 공백을 리턴한다
    if sort == 'created_at':
        reviews =  Review.objects.order_by('-created_at')
    elif sort == 'order_at' :
        reviews =  Review.objects.order_by('-order_at')
    else :
        # 좋아요 순 나열 좋아요 개수가 같으면 업데이트 순서로
        reviews =  Review.objects.annotate(like_count=Count('like_users')).order_by('-like_count', '-updated_at')

    page = request.GET.get('page', '1')
    paginator = Paginator(reviews, 4)
    posts = paginator.get_page(page)
    request.GET.get('item_name')
    context = {
        'reviews': reviews,
        'item_name': request.GET.get('item_name'),
        'posts' : posts,
        
    }
    return render(request, 'reviews/index.html', context)

   

    

@login_required # 로그인 한경우만 리뷰 작성 가능
def create(request, item_id):
    item_title = request.GET.get('item_title')
    print(request.GET.get('item_title'))
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            # 로그인한 유저 => 작성자네!
            review.user = request.user 
            review.item_id = item_id
            review.item_title = item_title
            review.save()
            messages.success(request, '리뷰 작성이 완료되었습니다.')
            return redirect('reviews:index')
    else: 
        review_form = ReviewForm()
    context = {
        'review_form': review_form,
        'item_title': request.GET.get('item_title')
    }
    return render(request, 'reviews/form.html', context=context)

# 리뷰 삭제
@login_required
def delete(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == 'POST':
        review.delete()
        return redirect('reviews:index')
    context = {
        'review':review
    }
    return render(request, 'reviews/detail.html', context)    



def detail(request, pk):
    review = get_object_or_404(Review, pk=pk)
    
    comment_form = CommentForm()
    # template에 객체 전달
    context = {
        'review': review,
        'comments': review.comment_set.all(),
        'comment_form': comment_form,
    }
    return render(request, 'reviews/detail.html', context)



@login_required
def update(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user == review.user:
        if request.method == "POST":
            # POST : input 값 가져와서, 검증하고, DB에 저장
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
                review_form.save()
                messages.success(request, "리뷰가 수정되었습니다.")
                return redirect("reviews:detail", review.pk)
            # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 review_form을 랜더링
        else:
            # GET : Form을 제공
            review_form = ReviewForm(instance=review)
        context = {
            "review_form": review_form,
           
        }
        return render(request, "reviews/form.html", context)
    else:

        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("reviews:detail", review.pk)




# 좋아요
@require_POST
def like(request, pk):
    review = get_object_or_404(Review, pk=pk)
    # print('hi') 요청 확인 위함
    # 만약 로그인한 유저(request.user)가 이 글을 좋아요 눌렀다면,
    if request.user in review.like_users.all():
        # 좋아요 삭제하고
        review.like_users.remove(request.user)
        is_liked = False
    else:  # 좋아요 누르지 않은 상태라면 좋아요에 추가하고
        review.like_users.add(request.user)
        is_liked = True
        # 상세 페이지로 redirect
    context = {"isLiked": is_liked, "likeCount": review.like_users.count()}
    return JsonResponse(context)



# 댓글 작성하기
@login_required
def comment_create(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect("reviews:detail", review.pk)



# 댓글 지우기
@login_required
def comment_delete(request, comment_pk, pk): # 마지막에 특정 리뷰에 대한 pk가 필요함
    comment = Comment.objects.get(pk=comment_pk)
    if request.user.is_authenticated and request.user == comment.user:
        comment.delete()
        return redirect("reviews:detail", pk)

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load humanize %}
{% block body %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">




{% endblock css %}
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300&display=swap" rel="stylesheet">
    <style>
        #review-content{
        font-family :'Dongle';
        font-size: xx-large;}

    </style>
</head>

<div>
    <!-- 아이템 이름 -->
    <div class='container'>
        <h2 class='text-center mb-5'> {{ review.title }}</h2>
        
        <!-- 사용자 이름 프로필 구현  -->
        <h4 style=' background-color:#ffe4c4; width: 420px; border-radius: 30rem; height: 35px; text-align:center; ' class='mb-5'> 구매 상품 : <a href="{% url 'items:detail' review.item_id %}" style='color:black;' class='text-decoration-none '>{{ review.item.title }}</a></h4>
        <div class="header d-flex">
            <!-- 프로필 -->
            <span class="username">
                <!-- 회원 정보 페이지로 넘어가기 -->
                <a class='text-decoration-none fw-bolder' style='color:black'
                    href="{% url 'accounts:mypage' review.user.pk %}">
                    <!-- 만악 회원 프로필 사진이 있으면 -->
                    
                    &nbsp;&nbsp;{{ review.user.username }}
                </a>
            </span>
            <!-- 팔로우 기능 -->

        </div>
        <!-- 제품 구매한 날 -->
        <p> 제품 구매한 날 : {{ review.order_at.isoformat }}</p>
        <!-- 리뷰 이미지 있으면 -->

        {% if review.image %}
        <div style='text-align:center'>
            <img src='{{ review.image.url }}' alt='{{ review.image }}' width="400" height="300"
                style='border-radius:4px;'>
        </div>
        {% comment %} 기본 이미지 {% endcomment %}
        {% else %}
        
        <div style='text-align:center'>
            
            <img src='{{ review.item.image_url }}' alt='{{ review.item.image_url }}' width="400" height="300"
                style='border-radius:4px;'>
        </div>
        
        {% endif %}
        <!-- 리뷰 내용 -->
        <p id="review-content" class="me-3-5 mt-3 text-break" style="font-family: 'Dongle';">{{ review.content }}</p>


        <!-- 좋아요 버튼 -->

        {% if request.user.is_authenticated %}
        <div class="d-flex justify-content-between">
            <form data-review-id='{{ review.pk }}' id='like-btn' class="like-heart">
                {% csrf_token %}
                <button style='background-color:transparent; border:none;' class='review-detail-like-btn' type='submit'>
                    {% if request.user in review.like_users.all %}
                    <i style='color:red' class="bi bi-heart-fill"></i>
                    <span id='review-like-user-cnt'>{{ review.like_users.count }}</span>
                    {% else %}
                    <i style='color:red' class="bi bi-heart"></i>
                    <span id='review-like-user-cnt'>{{ review.like_users.count }}</span>
                    {% endif %}
                </button>
            </form>
            <div class="d-flex justify-content-end">
                <a href="javascript:sendLinkFacebook()"><i class="bi bi-facebook me-2"></i></a>
                <a href="javascript:sendLinkTwitter()"><i class="bi bi-twitter"></i></a>
                <script>
                        function sendLinkFacebook(){
            var facebook_share_url = "https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}";
            window.open(facebook_share_url,
                        'Share on Facebook',
                        'scrollbars=no, width=500, height=500');
            } 
        
            function sendLinkTwitter(){
            var twitter_share_text="{{ post.title }}";
            var twitter_share_url="{{ request.build_absolute_uri }}";
            window.open("https://twitter.com/share?text="+twitter_share_text+"&url="+twitter_share_url,
                        'Share on Twitter',
                        'scrollbars=no, width=500, height=500');
            }
                </script>
            </div>
        </div>
        {% endif %}



        <!--리뷰 수정  -->
        {% if request.user == review.user %}
        <div class=' mt-2 d-flex'>
            {% comment %} 요청한 user가 리뷰를 작성한 user일 경우에 수정 및 삭제{% endcomment %}
            <p>
                <button type="button" class="btn btn-warning me-2">
                    <a href="{% url 'reviews:update' review.pk %}" style='text-decoration:none; color:white'
                        class='fw-bolder'>수정하기</a>
                </button>
            </p>
            <p>
            <form action="{% url 'reviews:delete' review.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger fw-bolder" value="삭제하기">
            </form>
            </p>
            
        </div>
        {% endif %}
        <!-- 댓글 -->
        <h4>댓글</h4>
        {% if request.user.is_authenticated %}
        <form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form layout='inline'%}
            <input type="submit" value="작성" class="btn btn-primary">
        </form>
        {% endif %}
        <!-- 댓글 순서대로 출력 -->
        {% for comment in comments %}
        <div class='py-3'>
            <div id="review-content" class="me-3-5 mt-3 text-break align-items-center" style="font-family: 'Dongle';">
                {{ comment.user.username }} : {{ comment.content }}
                <p id="review-content" class="d-flex justify-content-end" style="font-family: 'Dongle';" >{{ comment.created_at|naturaltime }}</p>
            </div>

            {% comment %} 댓글을 작성한 user가 리뷰를 쓴 유저인 경우 {% endcomment %}
            {% if user.is_authenticated and comment.user == request.user %}
            <form action="{% url 'reviews:comment_delete' review.pk comment.pk %}" method="POST" class="my-0">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-danger mt-2" value="삭제">
            </form>
            {% endif %}
            {% empty %}
            <br>
        </div>
        {% endfor %}












    </div>


</div>


{% block js %}
{% comment %} 리뷰 좋아요 비동기 자바스크립트 {% endcomment %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock js %}
<script>
    const likeBtn = document.querySelector('#like-btn')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    console.log(likeBtn)
    // (2) 좋아요 버튼을 클릭하면, 함수 실행
    likeBtn.addEventListener('click', function (event) {
        // 서버로 비동기 요청(axios)을 하고 싶음
        event.preventDefault()
        console.log(event.currentTarget.dataset.reviewId)
        axios({
            method: 'post',
            url: `/reviews/${event.currentTarget.dataset.reviewId}/like/`,
            headers: { 'X-CSRFToken': csrftoken },
        })
            .then(response => {
                console.log(response)
                console.log(response.data)
                const likeReview = document.querySelector('#like-btn > button > i')
                likeReview.classList.toggle('bi-heart')
                likeReview.classList.toggle('bi-heart-fill')
                // 다음 주석 처리한 내용과 동일
                // if (response.data.isLiked === true) {
                //     event.target.classList.add('bi-heart-fill')
                //     event.target.classList.remove('bi-heart')
                // } else {
                //     event.target.classList.add('bi-heart')
                //     event.target.classList.remove('bi-heart-fill')
                // }
                const likeCount = document.querySelector('#review-like-user-cnt')
                likeCount.innerText = response.data.likeCount
            })
    })
</script>

{% endblock %}

reviews/templates/reviews/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}

{% bootstrap_css %}

<h2 class='text-center mt-5'> 리뷰 작성 및 수정 페이지 </h2>

<div class='container py-3 mt-5'>
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form review_form %}
            {% bootstrap_button button_type="submit" content="리뷰 등록" %}
        </form>
    </div>    
</div>

{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
{% endblock css %}
<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300&display=swap" rel="stylesheet">
  <style>
      #review-content{
      font-family :'Dongle';
      font-size: xx-large;}

  </style>
</head>

{% comment %} 유저들의 리얼리뷰 {% endcomment %}
<div class="m-4 py-4 px-2" style="min-width:1250px;  ">
  <h2 class="text-center">
      <i class="bi bi-clipboard-check"></i>
    리뷰 목록
  </h2>
  {% comment %} 페이지네이션 {% endcomment %}
  <ul class="pagination justify-content-end">
    {% comment %} 이전 페이지 {% endcomment %}
    {% if posts.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous"
        style="border-color: chocolate; background-color: none; color: chocolate;">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#"
        style="border-color: chocolate; background-color: none; color: chocolate;">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% comment %} 페이지리스트 {% endcomment %}
    {% for page_number in posts.paginator.page_range %}
    {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %} 
    {% if page_number == posts.number %}
    <li class="page-item active" aria-current="page">
      <a class="page-link"
        style="font-family: 'SDSamliphopangche_Basic'; border-color: chocolate; color: white; background-color: chocolate;"
        href="?page={{ page_number }}">{{ page_number }}</a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}" style="font-family: 'SDSamliphopangche_Basic'; border-color: chocolate; color: chocolate;">{{ page_number }}</a>
      </li>
      {% endif %}
      {% endif %}
      {% endfor %}
      {% comment %} 다음 페이지 {% endcomment %}
      {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
  </ul>
  {% comment %} 순서 정렬 {% endcomment %}
  <select id="sort-select" onchange="location = this.value;" class='mb-3'>
    <option class="sort-created_at" value="?sort=created_at">ㅡㅡㅡㅡㅡㅡㅡ</option>
    <option class="sort-created_at" value="?sort=created_at">최근 작성글 순</option>
    <option class="sort-order_at" value="?sort=order_at">상품 구매 최신일순</option>
    <option class="sort-likes" value="?sort=likes">좋아요순</option>
  </select>
      {% comment %} 리뷰 카드들 {% endcomment %}
      <div class="row row-cols-4 g-2 ml-5"   >

        {% for review in posts %}
        <div class='col'>
          <article class="card h-100">
            <div class="card-header text-center" style="font-family: 'SDSamliphopangche_Basic';">

              {% comment %} 아이템 이름 {% endcomment %}
              <h4 class='mt-2'><a href="{% url 'items:detail' review.item_id %} "class='text-decoration-none  ' style='color:black ' >{{ review.item.title }}</a></h4>
            </div>

            <div class='d-flex justify-content-between m-2'>
              {% comment %} 사용자 이름 {% endcomment %}
              <a  href="{% url 'accounts:mypage' review.user.pk %}"class='text-decoration-none fw-bolder m-1' style='color:black'><div >{{ review.user.username }}</div></a>
              {% comment %} 상품 구매일{% endcomment %}
              <div>상품 구매일 : {{ review.order_at.isoformat }}</div>
            </div>
            {% comment %} 리뷰 이미지 {% endcomment %}
            {% if review.image %}
            <img src="{{ review.image.url }}" class="card-img-top" alt="..." style='height:278.4px; object-fit: cover;'>
            {% else %}

            {% comment %} 기본 이미지 {% endcomment %}
            <img src={{ review.item.image_url }} class="card-img-top" alt="{{ review.item.image_url }}" style='height:278.4px; object-fit: cover;'>
            {% endif %}
            <div class="card-body">
              <i style='color:red' class="bi bi-heart-fill  position-absolute bottom-0 start-0 m-3 mb-2 "> {{ review.like_users.count }}</i>
              {% comment %} 리뷰 제목 {% endcomment %}
              <h4 class="text-center" >
                {{ review.title }}
              </h4>
              <hr>
              {% comment %} 리뷰 내용 {% endcomment %}
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <p id="review-content" style="font-family: 'Dongle';" class="card-text" >
                    {{ review.content|truncatechars:50 }}</p>
                    
                  </li>
                  
                  
                </ul>
          
                  {% comment %} 좋아요 기능 {% endcomment %}

              </div>
              <div class="card-footer text-center" >
                <a href="{% url 'reviews:detail' review.pk %}" class='text-decoration-none' style='color:rgb(188,137,70); font-weight: bold;'>상세보기</a>
              </div>
            </article>
          </div>
          {% endfor %}
        </div>
</div>





{% block js %}
{% comment %} 리뷰 좋아요 비동기 자바스크립트 {% endcomment %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock js %}
<script>
  const likeBtnForms = document.querySelectorAll('.like-btn-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  
  likeBtnForms.forEach(function (likeBtnForm) {
    likeBtnForm.addEventListener('submit', function (event) {
      event.preventDefault()
      reviewId = event.target.dataset.reviewPk
      axios({
        method: 'post',
        url: `/reviews/${reviewId}/like/`,
        headers: { 'X-CSRFToken': csrftoken },
      }).then(function (response) {
        // 하트 아이콘 토글
        const likeITag = document.querySelector(`.like-btn-${reviewId} > i`)
        likeITag.classList.toggle('bi-heart-fill')
        likeITag.classList.toggle('bi-heart')
  
        // 좋아요 수 변경
        const likeCntTag = document.querySelector(`.like-btn-${reviewId} > span`)
        likeCntTag.innerText = response.data.likeCount
      })
    })
  })

    var getUrlParameter = function getUrlParameter(sParam) {
      var sPageURL = decodeURIComponent(window.location.search.substring(1)),
          sURLVariables = sPageURL.split('&'),
          sParameterName,
          i;
  
      for (i = 0; i < sURLVariables.length; i++) {
          sParameterName = sURLVariables[i].split('=');
  
          if (sParameterName[0] === sParam) {
              return sParameterName[1] === undefined ? true : sParameterName[1];
          }
      }
  };
  // 정렬방식 셀렉트 박스 유지
  $(document).ready(function(){
    var sort = getUrlParameter('sort');
    if(sort == 'likes'){
      $('.sort-likes').prop('selected', 'selected')
    }
    else if(sort == 'created_at'){
      $('.sort-created_at').prop('selected', 'selected')
    }
    else{
      $('.sort-order_at').prop('selected', 'selected')
    }
  });
</script>
{% endblock body %}