accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("mypage/<int:pk>/", views.mypage, name="mypage"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("follow/<int:pk>/", views.follow, name="follow"),
    
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:item_pk>/", views.detail, name="detail"),
    path("pick/", views.pick, name="pick"),  # 임시 경로
    path("picking/", views.picking, name="picking"),
    path("pick/delete", views.delete_picked, name="delete_picked"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path("accounts/", include("accounts.urls")),
    path("items/", include("items.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name ='reviews'


urlpatterns = [
    path('', views.index, name='index'),
    # 리뷰작성 
    path('<int:item_id>/create/', views.create, name='create'),
    # 리뷰 상세 조회
    path('<int:pk>/', views.detail, name='detail'),
    # 리뷰 수정
    path('<int:pk>/update/', views.update, name='update'),
    # 리뷰 삭제
    path('<int:pk>/delete/', views.delete, name='delete'),
    # 리뷰 좋아요
    path('<int:pk>/like/', views.like, name='like'),
    # 댓글 작성
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    # 댓글 삭제
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name ='comment_delete'),

]

items/models.py
from django.db import models
from django.conf import settings


class Item(models.Model):
    title = models.CharField(max_length=50)
    price = models.TextField()
    image_url = models.TextField()


# Item detail 모델 추가


class ItemDetail(models.Model):
    header_title = models.TextField()
    header_image = models.TextField()
    # 다음 필드들은 사용하지 않음
    # main_images_url01 = models.TextField()
    # main_images_url02 = models.TextField()
    # main_images_url03 = models.TextField()


# accounts에 ForeiginKey로 연결
class ItemPicked(models.Model):
    picked_item = models.ForeignKey(Item, on_delete=models.CASCADE)
    smashed = models.TextField()
    volume = models.TextField()
    amount = models.IntegerField()


class FactSheet(models.Model):
    fieldname = models.TextField()
    content = models.TextField()


class AboutThisCoffee(models.Model):
    title = models.TextField()
    content = models.TextField()

items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, ItemDetail, ItemPicked
from django.core.paginator import Paginator
from django.db.models import Avg, Count, Min, Sum
from reviews.models import Review
import csv

# 상품정보를 크롤링해서 model에 저장.


def index(request):
    item = Item.objects.all()
    # csv 파일에서 데이터를 불러온다
    if len(item) == 0:
        items_csv = open("items/items.csv", encoding="UTF-8")
        items_reader = csv.reader(items_csv)
        bulk_list = []
        for i in items_reader:
            bulk_list.append(
                Item(
                    title=i[1],
                    price=i[2],
                    image_url=i[3],
                )
            )
        Item.objects.bulk_create(bulk_list)
    # pagination
    ordered_item = Item.objects.order_by("pk")
    paginator = Paginator(ordered_item, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "item": item,
        "page_obj": page_obj,
    }
    return render(request, "items/index.html", context)


def detail(request, item_pk):
    # csv 파일에서 데이터를 불러온다
    item_detail_all = ItemDetail.objects.all()
    if len(item_detail_all) == 0:
        item_detail_csv = open("items/item_detail.csv", encoding="UTF-8")
        item_detail_reader = csv.reader(item_detail_csv)
        bulk_list = []
        for i in item_detail_reader:
            bulk_list.append(
                ItemDetail(
                    header_title=i[1],
                    header_image=i[2],
                ),
            )
        ItemDetail.objects.bulk_create(bulk_list)
    review = Review.objects.filter(item_id=item_pk)
    item_detail = ItemDetail.objects.get(pk=item_pk)
    item_details = ItemDetail.objects.all()
    context = {
        "item_detail": item_detail,
        "item_pk": item_pk,
        "review": review,
        "item_details": item_details,
    }
    return render(request, "items/detail.html", context)


# 담은 상품의 정보를 ItemPicked 테이블에 저장한 후 redirect한다.
def picking(request):
    # picked_items를 itemPicked 테이블에 추가한다
    if request.method == "POST":
        item_info = request.POST.get("item_picked")
        item_smashed = request.POST.get("smashed")
        item_volume = request.POST.get("volume")
        item_amount = request.POST.get("amount")
        picked_items = Item.objects.get(pk=item_info)
        picked_item_list = ItemPicked(
            picked_item=picked_items,
            amount=item_amount,
            smashed=item_smashed,
            volume=item_volume,
        )
        picked_item_list.save()

    return redirect("items:pick")


# 장바구니
def pick(request):
    picked = ItemPicked.objects.all()
    picked_count = picked.aggregate(count=(Count("id")))
    if len(picked) == 0:
        return render(request, "items/pick_none.html")
    else:
        context = {
            "picked": picked,
            "picked_count": picked_count["count"],
        }
        return render(request, "items/pick.html", context)


def delete_picked(request):
    item_checked = request.POST.get("checked_item")
    ItemPicked.objects.get(pk=item_checked).delete()
    return redirect("items:pick")


def before_order(request):
    # 주문금액보기
    # 장바구니 수량 변경
    return redirect("item:pick")


# 검색 기능
# 장바구니 수량 변경, 상품 삭제 구현

items/templates/items/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<header class="row gx-5" style="height:800px; margin: 0px 300px 0px 300px">
    <form class="col-6" style="width:470px; padding-top: 250px;" id='buy/pick-form' action="{% url 'items:picking' %}" method="POST">
        {% csrf_token %}
        <h1 class="fw-bold mb-5">{{item_detail.header_title}}</h1>
        <label class='form-label' for="">용량</label>
        <select class='form-select mb-3' name="volume" form="buy/pick-form">
            <option selected>= 용량 선택 =</option>
            <option value="200">200</option>
        </select>
        <label class='form-label' for="">분쇄도</label>
        <select class='form-select mb-3' name="smashed" form="buy/pick-form">
            <option selected>= 분쇄도 선택 : 가격 =</option>
            <option value="홀빈(갈지않음)">홀빈(갈지않음)</option>
            <option value="핸드드립/커피메이커">핸드드립/커피메이커</option>
            <option value="프렌치프레스">프렌치프레스</option>
            <option value="모카포트">모카포트</option>
            <option value="에어로프레스">에어로프레스</option>
            <option value="에스프레소머신">에스프레소머신</option>
            <option value="콜드브루/더치">콜드브루/더치</option>
        </select>
        <div class="d-flex justify-content-end mb-2">
            <div class="mb-0 me-2 pt-2 align-middle">수량</div>
            <input type="text" name="amount" class="form-control border border-grey text-center" style="width:45px">
        </div>
        <div class="d-flex justify-content-between">
            <button id="buy-button" type="button" class="btn btn-dark rounded-0"><a class="text-decoration-none text-white" href="">구매하기</a></button>
            <!-- 버튼을 누르면 페이지의 item_pk 값이 전송된다. -->
            <!-- popover 작동 안 됨 -->
            <button id="pick-button" type="submit" 
                class="btn btn-outline-dark rounded-0" name="item_picked" value="{{item_pk}}"
                data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="추가되었습니다">
                장바구니
            </button>
            <!-- 버튼을 누르면 장바구니에 담겼다는 popover창이 뜬다 -->
        </div>
    </form>
    <!-- header 우측 -->
    <div class="col-6" style="padding-left: 150px;">
        <img src={{item_detail.header_image}} alt="상품이미지">
    </div>

</header>
<!-- header, main 사이 : fact_sheet, about_this_coffee -->
<!-- <div class="row bg-white py-5" style="height:380px; margin: 0px 300px 0px 300px;">
    <div class="col-4 ps-5" >
        <p class="fw-semibold">FACT SHEET</p>
        <div class="mt-5">
            <div class="d-flex flex-column">
                <span>생산자</span>
                <span class="mt-2">농장</span>
                <span class="mt-2">지역</span>
                <span class="mt-2">품종</span>
                <span class="mt-2">가공</span>
                <span class="mt-2">로스팅</span>
            </div>
            <div class="ms-3">
                <p></p>
                <p></p>
                <p></p>
                <p></p>
                <p></p>
                <p></p>
            </div>
        </div>
    </div>
    <div class="col-8 ps-5 border-start">
        <p class="fw-semibold">ABOUT THIS COFFEE</p>
        <div>
            <div class="mt-5">
                <p>title </p>
                <p>content </p>
            </div>
        </div>
    </div>
</div> -->

<main class='mt-5 pt-5' style='margin: 0px 300px 0px 300px;'>
    <div id="carouselExampleControls" class="carousel slide ms-5 ps-5" data-bs-ride="carousel">
        <div class="carousel-inner">
        <!-- 다른 모든 상품들 링크 carousel로 바꾸기 : 3개씩 -->
          <div class="carousel-item active">
            <div class="d-flex">
                <img src={{item_details.1.header_image}} class="d-block" alt="..." style="height: 400px;">
                <img src={{item_details.2.header_image}} class="d-block" alt="..." style="height: 400px;">
                <img src={{item_details.12.header_image}} class="d-block" alt="..." style="height: 400px;">
            </div>
        </div>
        <div class="carousel-item">
            <div class="d-flex">
                <img src={{item_details.13.header_image}} class="d-block" alt="..." style="height: 400px;">
                <img src={{item_details.5.header_image}} class="d-block" alt="..." style="height: 400px;">
                <img src={{item_details.6.header_image}} class="d-block" alt="..." style="height: 400px;">
            </div>
        </div>
        <div class="carousel-item">
            <div class="d-flex">
                <img src={{item_details.7.header_image}} class="d-block" alt="..." style="height: 400px;">
                <img src={{item_details.8.header_image}} class="d-block" alt="..." style="height: 400px;">
                <img src={{item_details.17.header_image}} class="d-block" alt="..." style="height: 400px;">
            </div>
          </div>
        
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    <!-- <div class="d-flex bg-light align-items-center mt-5" >
        <img src="https://dummyimage.com/800x1200/8a8a8a/fff"alt="image">
        <div class="ms-5">
            <h5>title </h5>
            <p>content </p>
        </div>
    </div> -->
    <!-- <div class="d-flex bg-light align-items-center mt-5" >
        <img src="https://dummyimage.com/800x1200/8a8a8a/fff" alt="image">
        <div class="ms-5">
            <h5>title </h5>
            <p>content </p>
        </div>
    </div>
    <div class="d-flex bg-light align-items-center mt-5" >
        <img src="https://dummyimage.com/800x1200/8a8a8a/fff" alt="image">
        <div class="ms-5">
            <h5>title </h5>
            <p>content </p>
        </div>
    </div> -->
    <div class="p-5 m-5">
        <div class="my-5" style="height:400px">
            <h1 class="mb-3">SHIPPING & DELIVERY</h1>
            <div class="mt-5">
                <!-- dropdown 추가 -->
                <div class="p-4 bg-light fw-bold">배송안내</div>
                <div class="p-4 bg-light fw-bold">교환/환불 안내</div>
                <div class="p-4 bg-light fw-bold">카카오톡 문의</div>
            </div>
        </div>
        <!-- review -->
        <div class="mt-5">
            <h1>REVIEW</h1>
            <div class="d-flex align-items-start justify-content-center">
                <table class="table table-hover text-center">
                    <thead>
                        <tr>
                            <th style="width:5%"scope="col">번호</th>
                            <th scope="col">제목</th>
                            <th style="width:15%" scope="col">작성자</th>
                            <th style="width:25%"scope="col">작성일</th>
                          </tr>
                    </thead>
                    <tbody class="bg-light">
                    {% for i in review %}
                        <tr>
                            <th class="py-3" scope="row">{{i.pk}}</th>
                            <hr>
                            <td class="py-3"><a href="{% url 'reviews:detail' i.pk %}" class='text-decoration-none ' style='color:black '>{{i.title}}</a></td>
                            <hr>
                            <td class="py-3"><a href="{% url 'accounts:mypage' i.user.pk %}" class='text-decoration-none ' style='color:black '>{{i.user.username}}</a></td>
                            <hr>
                            <td class="py-3">{{i.created_at}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
        <a href="{% url 'reviews:create' item_pk  %}" class='text-decoration-none d-flex justify-content-end mb-5' style='color:black '><i class="bi bi-pencil">리뷰 작성</i></a>
        </div>
    <!-- <div class="mt-5 p-5 bg-light">
        <h1 class="pt-5">RECOMMEND</h1>
        <div class="my-5 p-5 d-flex justify-content-center bg-secondary" style="width:1100 px;height:700px;">
            <img src="" alt="">
            <img src="" alt="">
            <img src="" alt="">
        </div>
    </div> -->
</main>
<footer id='detail-footer' class='d-flex align-items-center bg-light text-white'>
    <div style="margin-left: 200px;">
        <h1 class="fw-bold">SUBSCRITIONS</h1>
        <h4 class="fw-bold my-3">빈 브라더스 커피 구독 서비스</h4>
        <p style="line-height:25px">무궁무진한 커피 세계를 탐험하세요.<br>
            매월 새로운 추천 커피를 할인된 가격에 무료배송으로<br>
            모자르거나 남는 걱정없이 스케줄을 조정하고 정지할 수 있어요.
        </p>
        <div class="d-flex mt-5">
            <button type="button" class="btn rounded-0 bg-white fw-bold" style="padding:10px 50px 10px 50px">구독하기</button>
            <button type="button" class="btn rounded-0 text-white border-white ms-2 fw-bold" style="padding:10px 50px 10px 50px">샘플러신청</button>
        </div>
    </div>
</footer>
{% endblock %}

items/templates/items/index.html
<!-- 빈브라더스 외의 다른 커피점 상품도 추후 추가 -->
{% extends 'base.html' %}
{% block body %}
<!-- 상품 카테고리 -->
<div id="item-category" class="fs-5">
    <p><a href="" class="text-decoration-none text-dark">NEW</a></p>
    <p><a href="" class="text-decoration-none text-dark">원두</a></p>
    <p><a href="" class="text-decoration-none text-dark">드립백</a></p>
    <p><a href="" class="text-decoration-none text-dark">콜드브루</a></p>
    <p><a href="" class="text-decoration-none text-dark">캡슐커피</a></p>
    <p><a href="" class="text-decoration-none text-dark">선물세트</a></p>
    <p><a href="" class="text-decoration-none text-dark">커피용품</a></p>
    <p><a href="" class="text-decoration-none text-dark">클래스/워크샵</a></p>
</div>

<!-- 상품 목록 -->
<div class="row row-cols-1 row-cols-md-3 g-4 my-5" style="margin: 0px 300px 0px 300px;">
    {% for i in page_obj %}
    <a href="{% url 'items:detail' i.pk %}" class='text-dark text-decoration-none'>
    <div class="col">   
        <div id='items' class="card border border-0 p-3">
            <img src={{i.image_url}} alt={{i.title}}>
            <div class="card-body">
                <h5 class="card-title fw-semibold text-center">{{i.title}}</h5>
                <!-- <div class="card-text text-center">상품영문명칭</div> -->
            </div>
        </div>
    </div>
    </a>
    {% endfor %}
</div>

<ul id="pagination" class="d-flex my-5 d-flex justify-content-center p-5">
    <li class="mx-2 rounded"><a class="border border-0 text-muted" href="?page=1">1</a></li>
    <li class="mx-2 rounded"><a class="border border-0 text-muted" href="?page=2">2</a></li>
    <li class="mx-2 rounded"><a class="border border-0 text-muted" href="?page=3">3</a></li>
    <li class="mx-2 rounded"><a class="border border-0 text-muted" href="?page=4">4</a></li>
</ul>

{% endblock %}

items/templates/items/pick.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="row" style="margin: 100px 300px 100px 300px;" >
    <div class="col-2">
        <h1 class="fw-bold">장바구니</h1>
        <ul class="list-group mt-4">
            <li class="list-group-item border border-0 px-0 fs-5">
                <span class="fw-bold me-2">01</span> 장바구니
            </li>
            <li class="list-group-item border border-0 px-0 fs-5">
                <span class="fw-bold me-2">02</span> 주문서작성/결제
            </li>
            <li class="list-group-item border border-0 px-0 fs-5">
                <span class="fw-bold me-2">03</span> 주문완료
            </li>
        </ul>
    </div>
    <div class="col-10" style="padding-left: 150px;">
        <h3 class="fw-bold">장바구니</h3>
        <table id="pick-table" class="table mt-4">
            <thead>
                <tr>
                    <th scope="col" class="text-center"><input type="checkbox" form="pick_item_pick-form"></th>
                    <th scope="col" class="text-center">상품명/옵션</th>
                    <th scope="col" class="text-center">수량</th>
                    <th scope="col" class="text-center">상품금액</th>
                    <th scope="col" class="text-center">할인/적립</th>
                    <th scope="col" class="text-center">합계금액</th>
                </tr>
            </thead>
            <tbody>
                {% for i in picked %}
                <tr style="padding: 30px 0px 30px 0px;">
                        <th class="text-center align-middle"><input type="checkbox" name="checked_item" value="{{i.pk}}" form="pick-delete-form"></th>
                    <td class="pt-4 d-flex">
                        <img src={{i.picked_item.image_url}} alt="item_image" style="height: 90px;">
                        <div id="picked_item_info">
                            <p class="fw-bold mb-2" style="padding-left:40px;">{{i.picked_item.title}}</p>
                            <p class="mb-0 text-muted" style="font-size: 15px; padding-left:40px;">용량 <span class="fw-semibold ms-2">{{i.volume}}</span></p>
                            <p class="mb-0 text-muted" style="font-size: 15px; padding-left:40px;">분쇄도 <span class="fw-semibold ms-2">{{i.smashed}}</span></p>
                        </div>
                    </td>
                    <td class="text-center py-3 align-middle">
                    <p class="mb-2">{{i.amount}}</p>
                    <p class="mb-0">
                        <button class="btn btn-light m-0" data-bs-toggle="modal" data-bs-target="#exampleModal" style="font-size: 14px;">
                        옵션/수량 변경
                        </button>
                        <!-- modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h1 class="modal-title fs-5 fw-bold" id="exampleModalLabel">옵션선택</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="d-flex">
                                        <img src="{{i.picked_item.image_url}}" alt="item_image" style="height: 100px;" class="mt-1">
                                        <div id="picked_item_info">
                                            <p class="fw-bold mb-2 ms-2 mt-3">{{i.picked_item.title}}</p>
                                            <p class="mb-0 text-muted ms-2" style="font-size: 15px;">배송비 3000원 </p>
                                            
                                        </div>
                                    </div>
                                    <form action="{% url 'items:picking' %}" method="POST">
                                        <div style="width:470px">
                                        <p class="text-start my-2">용량</p>
                                        <select class='form-select mb-3' id="volume1"name="" form="buy/pick-form">
                                            <option selected>= 용량 선택 =</option>
                                            <option value="200">200</option>
                                        </select>
                                        <p class="text-start my-2">분쇄도</p>
                                        <select class='form-select mb-5' name="" form="buy/pick-form">
                                            <option selected>= 분쇄도 선택 : 가격 =</option>
                                            <option value="홀빈(갈지않음)">홀빈(갈지않음)</option>
                                            <option value="핸드드립/커피메이커">핸드드립/커피메이커</option>
                                            <option value="프렌치프레스">프렌치프레스</option>
                                            <option value="모카포트">모카포트</option>
                                            <option value="에어로프레스">에어로프레스</option>
                                            <option value="에스프레소머신">에스프레소머신</option>
                                            <option value="콜드브루/더치">콜드브루/더치</option>
                                        </select>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                <button type="button" type="submit" class="btn btn-secondary" data-bs-dismiss="modal">확인</button>
                                </div>
                            </div>
                            </div>
                        </div>
                    </p>
                    </td>
                    <td class="text-center py-3 align-middle">{{i.picked_item.price}}</td>
                    <td class="text-center py-3 align-middle"></td>
                    <td class="text-center py-3 align-middle">{{i.picked_item.price}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div id="pick-deliver" class="bg-light py-4 d-flex justify-content-center align-items-center fs-5">
            <dl class="p-4 text-center">
                <dt class="fw-light">주문 금액</dt>
                <dd id='price' class="mt-3 fw-bold">{{picked.0.picked_item.price}}</dd>
            </dl>
            <span class="p-4">+</span>
            <dl class="p-4 text-center">
                <dt class="fw-light">배송비</dt>
                <dd class="mt-3 fw-bold">0원</dd>
            </dl>
            <span class="p-4">=</span>
            <dl class="p-4 text-center">
                <dt class="fw-light">합계</dt>
                <dd id='order-price' class="mt-3 fw-bold">{{picked.0.picked_item.price}}</dd>
            </dl>
        </div>
        <form id='pick-delete-form'action="{% url 'items:delete_picked' %}" method='POST'>
        {% csrf_token %}
        <div id='pick_action' class="d-flex justify-content-between text-muted fs-6 mt-2">
            <button class='btn round fw-semibold'><a href="{% url 'items:index' %}">쇼핑계속하기</a></button>
            <div>
                <button id='order-price'class='btn round fw-semibold' type="submit" form="">주문 금액 보기</button>
                <button class='btn round fw-semibold' type="submit" form="pick-delete-form">선택 상품 삭제</button>
            </div>
        </div>
        </form>
            <!-- <div class="d-flex">
                <button type="button" class="py-1 px-3">선택상품주문</button>
                <button type="button" class="py-1 px-3">전체상품주문</button>
            </div> -->
        </div>
    </div>
    <!-- <script>
        const orderPriceShow = document.getElementById('order-price')
        function sum_(){
            const price = document.getElementById('price')
            const order_price = document.getElementById('order-price')
            
        }
        orderPriceShow.addEventListener('click',)
    </script> -->

{% endblock %}

items/templates/items/pick_none.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="row" style="margin: 100px 300px 100px 300px;" >
    <div class="col-2">
        <h1 class="fw-bold">장바구니</h1>
        <ul class="list-group mt-4">
            <li class="list-group-item border border-0 px-0 fs-5">
                <span class="fw-bold me-2">01</span> 장바구니
            </li>
            <li class="list-group-item border border-0 px-0 fs-5">
                <span class="fw-bold me-2">02</span> 주문서작성/결제
            </li>
            <li class="list-group-item border border-0 px-0 fs-5">
                <span class="fw-bold me-2">03</span> 주문완료
            </li>
        </ul>
    </div>
    <div class="col-10" style="padding-left: 150px;">
        <h3 class="fw-bold">장바구니</h3>
        <table id="pick-table" class="table mt-4">
            <thead>
                <tr>
                    <th scope="col" class="text-center"><input type="checkbox" value="{{picked}}"></th>
                    <th scope="col" class="text-center">상품명/옵션</th>
                    <th scope="col" class="text-center">수량</th>
                    <th scope="col" class="text-center">상품금액</th>
                    <th scope="col" class="text-center">할인/적립</th>
                    <th scope="col" class="text-center">합계금액</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="6" class="text-center p-5">장바구니에 상품이 없습니다.</td>
                </tr>
            </tbody>
        </table>
        <div id="pick-deliver" class="bg-light py-4 d-flex justify-content-center align-items-center fs-5">
            <dl class="p-4 text-center">
                <dt class="fw-light">주문 금액</dt>
                <dd class="mt-3 fw-bold">0원</dd>
            </dl>
            <span class="p-4">+</span>
            <dl class="p-4 text-center">
                <dt class="fw-light">배송비</dt>
                <dd class="mt-3 fw-bold">0원</dd>
            </dl>
            <span class="p-4">=</span>
            <dl class="p-4 text-center">
                <dt class="fw-light">합계</dt>
                <dd class="mt-3 fw-bold">0원</dd>
            </dl>
        </div>
        <div id='pick_action' class="d-flex justify-content-between text-muted fs-6 mt-2">
            <button class='btn round fw-semibold' href="{% url 'items:index' %}">쇼핑계속하기</button>
            <button class='btn round fw-semibold' type="submit">선택 상품 삭제</button>
        </div>
        <!-- <div class="d-flex">
            <button type="button" class="py-1 px-3">선택상품주문</button>
            <button type="button" class="py-1 px-3">전체상품주문</button>
        </div> -->
    </div>
</div>

{% endblock %}

items/templates/items/test.html
<!-- 빈브라더스 외의 다른 커피점 상품도 추후 추가 -->
{% extends 'base.html' %}
{% block body %}
<!-- 상품 카테고리 -->
<div class="d-flex align-itmes-center fs-5 text-muted fw-light" style="margin-top:1rem">
    <p class="ms-5">NEW</p>
    <p class="ms-5">원두</p>
    <p class="ms-5">드립백</p>
    <p class="ms-5">콜드브루</p>
    <p class="ms-5">캡슐커피</p>
    <p class="ms-5">선물세트</p>
    <p class="ms-5">커피용품</p>
    <p class="ms-5">클래스/워크샵</p>
</div>
<!-- 상품 목록 -->
<div class="row row-cols-1 row-cols-md-3 g-4 my-5" style="margin: 0px 300px 0px 300px;">
    {% for i in item %}
    <a href="{% url 'items:detail' i.pk %}" class='text-dark text-decoration-none'>
    <div class="col">   
        <div class="card border border-0 p-3">
            <img src={{i.image_url}} alt="상품이미지예정">
            <div class="card-body">
                <h5 class="card-title fw-semibold text-center">{{i.title}}</h5>
                <div class="card-text text-center">상품영문명칭</div>
            </div>
        </div>
    </div>
    </a>
    {% endfor %}
</div>

<ul class="pagination my-5 d-flex justify-content-center p-5">
    <li class="page-item active" aria-current="page">
    <span class="page-link">1</span>
    </li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">4</a></li>
</ul>

{% endblock %}