accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("mypage/<int:pk>/", views.mypage, name="mypage"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("follow/<int:pk>/", views.follow, name="follow"),
    
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:item_pk>/", views.detail, name="detail"),
    path("pick/", views.pick, name="pick"),  # 임시 경로
    path("picking/", views.picking, name="picking"),
    path("pick/delete", views.delete_picked, name="delete_picked"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path("accounts/", include("accounts.urls")),
    path("items/", include("items.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name ='reviews'


urlpatterns = [
    path('', views.index, name='index'),
    # 리뷰작성 
    path('<int:item_id>/create/', views.create, name='create'),
    # 리뷰 상세 조회
    path('<int:pk>/', views.detail, name='detail'),
    # 리뷰 수정
    path('<int:pk>/update/', views.update, name='update'),
    # 리뷰 삭제
    path('<int:pk>/delete/', views.delete, name='delete'),
    # 리뷰 좋아요
    path('<int:pk>/like/', views.like, name='like'),
    # 댓글 작성
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    # 댓글 삭제
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name ='comment_delete'),

]

pjt/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

pjt/templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Java chip</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'items/style.css' %}">
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/128/924/924514.png">
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    {% block script %}{% endblock script %}
</head>


<!-- nav-bar -->

<body>
    <nav class="sticky-top">
      <div class="wrapper">
        <div class="logo"><a href="{% url 'index' %}">Java chip</a>&nbsp;&nbsp;&nbsp;
        <img src="https://cdn-icons-gif.flaticon.com/6172/6172525.gif" alt="" width="30px" href=""></img>
        </div>
        <input type="radio" name="slider" id="menu-btn">
        <input type="radio" name="slider" id="close-btn">
        <ul class="nav-links">
          <li><div>
            <a href="" class="desktop-item"><b>커피구독</b></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'items:index' %}" class="desktop-item"><b>SHOP</b></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="" class="desktop-item"><b>ABOUT</b></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
            <div class="mega-box">
              <div class="content">
                <div class="row">
                  <ul class="mega-links">
                    <li><a href=""><b>샘플러신청</b></a></li>
                    <li><a href=""><b>구독신청</b></a></li>
                  </ul>
                </div>
                <div class="row">
                  <ul class="mega-links">
                    <li><a href=""><b>NEW</b></a></li>
                    <li><a href=""><b>원두</b></a></li>
                    <li><a href=""><b>드립백</b></a></li>
                    <li><a href=""><b>콜드브루</b></a></li>
                    <li><a href=""><b>캡슐커피</b></a></li>
                    <li><a href=""><b>선물세트</b></a></li>
                    <li><a href=""><b>커피용품</b></a></li>
                    <li><a href=""><b>클래스/워크샵</b></a></li>
                  </ul>
                </div>
                <div class="row">
                  <ul class="mega-links">
                    <li><a href=""><b>브랜드</b></a></li>
                    <li><a href=""><b>매장안내</b></a></li>
                    <li><a href=""><b>납품 및 컨설팅</b></a></li>
                    <li><a href=""><b>오피스 커피구독</b></a></li>
                    <li><a href=""><b>커피위키</b></a></li>
                    <li><a href=""><b>아카이브</b></a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div>
              {% if request.user.is_authenticated %}
              <li>
                <a aria-current="page" href="{% url 'reviews:index' %}"><b>리뷰목록</b></a>
              </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <li>
                <a aria-current="page"  href="{% url 'accounts:mypage' request.user.pk %}"><b>{{ request.user }}</b></a>
              </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <li>
                <a aria-current="page" href="{% url 'accounts:logout' %}"><b>로그아웃</b></a>
              </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <li>
                <a href="{% url 'items:pick' %}"><img src="https://cdn-icons-gif.flaticon.com/6416/6416388.gif" alt="장바구니" width="30px"></img></a></li>
            </li>
              </div>
              {% else %}
            <li><a aria-current="page" href="{% url 'reviews:index' %}"><b>리뷰목록</b></a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <li><a aria-current="page" href="{% url 'accounts:login' %}"><b>로그인</b></a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <li><a aria-current="page" href="{% url 'accounts:signup' %}"><b>회원가입</b></a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <li><a aria-current="page" href="{% url 'items:pick' %}"><img src="https://cdn-icons-gif.flaticon.com/6416/6416388.gif" alt="장바구니" width="30px"></img></a></li>
          </li>
          {% endif %}
          
        </ul>
      </div>
    </nav>
  </body>{% block body %}{% endblock body %}
    
  {% bootstrap_javascript %}
  
  
    <!-- footer -->

    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
      
            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            COPYRIGHT(C) Java chip. ALL RIGHTS RESERVED. HOSTING BY 19팀(주). DESIGN BY 19팀
        </div>
        <!-- Copyright -->
      </footer>
</html>

pjt/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<!-- carousel -->

<div id="carouselExampleCaptions" class="carousel slide" data-interval="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/5d8d8d7d06e357c6e23b3b9d64147ec7_36000.jpg" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:white;"><b>이벤트</b></h5><br>
        <h1 style="color:white;"><b>꿈의 홈 카페를<br>세팅해드립니다.</b></h1><br><br><br><br><br><br><br>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/3d88deb4ff3475cb1e4e3b74d87f4155_45847.jpg" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:black;"><b>11월의 싱글 오리진</b></h5><br>
        <h1 style="color:black;"><b>다채로운 개성의<br>과테말라, 페루, 에티오피아</b></h1><br><br><br><br><br><br><br>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/b867a98ed2b1939bbecbf10f4553f1c9_76991.jpg" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:white;"><b>오피스 커피 구독</b></h5><br>
        <h1 style="color:white;"><b>Java chip 커피를<br>사무실에서도</b></h1><br><br><br><br><br><br><br>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<!-- banner 1 -->

<br><br><br><br><div class="card text text-black">
    <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/f382428917061c0cee0bfe3a152238b5_28332.jpg" height="750px" class="card-img" alt="...">
    <div class="card-img-overlay"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/3ab2890cdf908809db68740f6a638871_98820.png"  alt="커피 구독 서비스" title="커피 구독 서비스">
        <div><br>
                <h4 class="card-text"><b>Java chip 커피 구독 서비스</b></h4><br>
                <p class="card-text"><b>Java chip과 함께 무궁무진한 커피 세계를 탐험하세요.<br>
                매월 새로운 추천 커피를 할인된 가격에 무료배송으로.<br>
                모자라거나 남는 걱정없이 매번 변경하거나 정지할 수 있어요.</b></p>
                <a href="" class="btn10">
                  <span><b>구독하기</b></span>
               <div class="transition"></div>
             </a>
             <a href="" class="btn10">
              <span><b>샘플러 신청</b></span>
              <div class="transition"></div>
              </a>
        </div>
    </div>
  </div>

<!-- seasonal -->
<div class="container">
  <br><br><br><br><div class="goods_list_tit">
      <div>&nbsp;&nbsp;<img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/40f59d46d6736451fdf0d8111cd8d714_74257.png" alt="SEASONAL"/></div>
      <br><p><b>&nbsp;&nbsp;매월 새롭게 소개하는 시즈널 커피</b></p>
  </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <div class="col">
        <div class="card">
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/goods/22/10/43/1000000216/1000000216_detail_019.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center"><b>과테말라 전 윗츠</b></h5>
            <p class="card-text" style="text-align: center">Guatemala Tzun Witz</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/goods/22/10/43/1000000215/1000000215_detail_052.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center"><b>에티오피아 콩가 워테</b></h5>
            <p class="card-text" style="text-align: center">Ethiopia Konga Wote</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/goods/22/10/43/1000000214/1000000214_detail_094.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center"><b>페루 라 몬테냐</b></h5>
            <p class="card-text" style="text-align: center">Peru La Montaña</p>
          </div>
        </div>
      </div>
  </div>


  <!-- seasonaless -->

  <br><br><br><br><div class="goods_list_tit">
      <div>&nbsp;&nbsp;<img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/d916a918805c58cc7937fa4a4dbbb72f_18038.png" alt="SEASONALESS"/></div>
      <br><p><b>&nbsp;&nbsp;Java chip의 시그니처 블렌드</b></p>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
      <div class="col">
        <div class="card">
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/goods/21/11/45/1000000082/1000000082_detail_083.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center"><b>멕시코 카바노크 디카페인</b></h5>
            <p class="card-text" style="text-align: center">Mexico CABONOCH Decaf</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/goods/21/07/30/1000000031/1000000031_detail_082.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center"><b>블랙수트</b></h5>
            <p class="card-text" style="text-align: center">Black Suit</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/goods/21/07/30/1000000025/1000000025_detail_015.png" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center"><b>벨벳화이트</b></h5>
            <p class="card-text" style="text-align: center">Velvet White</p>
          </div>
        </div>
      </div>
  </div>
</div>
<!-- DRIP BAG -->
<br><br><br><br><div class="card text-bg-dark">
    <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/91fb7ff7a3051356620f0865c83c648c_18278.jpg" class="card-img" alt="..." style="height: 600px;">
      <div class="card-img-overlay"><br><br><br><br><br><br><br><br>
          <img src="https://cdn-pro-web-210-60-godomall.spdycdn.net/ablestory_godomall_com/data/skin/front/designwib_C/img/banner/13d2c706a694564d9fdd7425fd24c8ae_29132.png"  alt="드립백" title="드립백">
          <div><br>
      <h4 class="card-text"><b></b>Java chip 드립백</b></h4><br>
      <p class="card-text">Java chip 커피를 더욱 간편하게 즐겨보세요.<br>
        7가지 종류로 취향과 기분에 따라 골라 마실 수 있습니다.<br>
        집과 사무실에 두고 마시거나 선물하기도 좋습니다.</p>
        <a href="" class="btn10" style="color:white">
          <span><b>바로 구매</b></span>
      <div class="transition"></div>
      </a>
      <a href="" class="btn10" style="color:white" >
        <span><b>장바구니</b></span>
        <div class="transition"></div>
      </a>
        </div>
    </div>
  </div>

  

{% endblock body %}