accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("mypage/<int:pk>/", views.mypage, name="mypage"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("follow/<int:pk>/", views.follow, name="follow"),
    
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path("accounts/", include("accounts.urls")),
    path("items/", include("items.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField

from imagekit.processors import Thumbnail

from imagekit.processors import ResizeToFill


class User(AbstractUser):
    image_thumbnail = ProcessedImageField(
        upload_to="accounts/images/",
        blank=True,
        processors=[ResizeToFill(160, 90)],
        format="JPEG",
        options={"quality": 95},
    )
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    pass 


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile"
    )
    image = models.ImageField(
        upload_to="accounts/images/",
        blank=True,
    )
    thumbnail = ProcessedImageField(
        upload_to="accounts/images/",
        blank=True,
        processors=[Thumbnail(300, 400)],
        format="JPEG",
    )
    status = models.CharField(max_length=100, blank=True)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            "username",
            "password1",
            "password2",
            "last_name",
            "email",
        )
        labels = {
            "username": "아이디",
            "password1": "비밀번호",
            "password2": "비밀번호 확인",
            "last_name": "이름",
            "email": "이메일",
        }

class UpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "email",
            "first_name",
            "last_name",
        )
        labels = {
            "email": "이메일",
            "first_name": "성",
            "last_name": "이름",
        }

accounts/views.py
from .models import User, Profile
from django.shortcuts import render, redirect
from accounts.forms import SignupForm, UpdateForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm 
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import JsonResponse



# Create your views here.

def index(request):
    users = User.objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)

def signup(request):
    if request.method =="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("/")
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "/")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)

def logout(request):
    auth_logout(request)
    return redirect("/")

@login_required
def update(request):
    if request.method == "POST":
        form = UpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = UpdateForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:update")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password.html", context)

@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("/")

def mypage(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/mypage.html", context)

def profile(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/profile.html", context)

@login_required
def follow(request, pk):
    if request.user.is_authenticated:
            User = get_user_model()
            me = request.user
            you = User.objects.get(pk=pk)
            if me != you:
                if you.followers.filter(pk=me.pk).exists():
                    you.followers.remove(me)
                    is_followed =False
                else :
                    you.followers.add(me)
                    is_followed = True
                context ={
                    'is_followed' : is_followed,
                    'followers_count' :  you.followers.count(),
                    'followings_count' : you.followings.count(),
                }
                return JsonResponse(context)
            return redirect('accounts:mypage', you.username)
    return redirect('accounts:login')

accounts/templates/accounts/follow.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<h1>follow</h1>

{% if request.user != user %}
    {% comment %} 스스로는 팔로우 불가 {% endcomment %}
    <a href="{% url 'accounts:follow' user.pk %}" class="btn btn-primary float-end">
        {% if request.user in user.followers.all %}
        팔로우 취소
        {% else %}
        팔로우
        {% endif %}

    </a>
    {% endif %}
    <p> 
        팔로우
        {{ user.followings.count }}
        | 팔로워
        {{ user.followers.count }}
     </p>
    


{% endblock  %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<!--삭제할 수도 있음-->
<h1>account index</h1>

{% if user.is_authenticated %}
{% else %}
    <p>회원이신가요?</p>
    <p>로그인</p>
{% endif %}
    <p>아직 회원이 아니신가요?</p>
    


{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<body>
  <header>
      <h2>&nbsp;&nbsp;Login</h2>
  </header><br>

  <form action="{% url 'accounts:login' %}" method="POST">

      <div class="input-box">
          <input id="username" type="text" name="username" placeholder="아이디">
          <label for="username">&nbsp;&nbsp;아이디</label>
      </div>

      <div class="input-box">
          <input id="password" type="password" name="password" placeholder="비밀번호">
          <label for="password">&nbsp;&nbsp;비밀번호</label>
      </div>
      &nbsp;&nbsp;<input type="submit" value="로그인" class="button">
      {% csrf_token %}
  </form>

</body>

<!-- 카카오 로그인 주석처리  -->
<!-- <ul>
	<li onclick="kakaoLogin();">
      <a href="javascript:void(0)">
          <span>카카오 로그인</span>
      </a>
	</li>
	<li onclick="kakaoLogout();">
      <a href="javascript:void(0)">
          <span>카카오 로그아웃</span>
      </a>
	</li>
</ul>
<!-- 카카오 스크립트 -->
<!-- <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
<script>
Kakao.init(''); //발급받은 키 중 javascript키를 사용해준다.
console.log(Kakao.isInitialized()); // sdk초기화여부판단
//카카오로그인
function kakaoLogin() {
    Kakao.Auth.login({
      success: function (response) {
        Kakao.API.request({
          url: '/v2/user/me',
          success: function (response) {
        	  console.log(response)
          },
          fail: function (error) {
            console.log(error)
          },
        })
      },
      fail: function (error) {
        console.log(error)
      },
    })
  }
//카카오로그아웃  
function kakaoLogout() {
    if (Kakao.Auth.getAccessToken()) {
      Kakao.API.request({
        url: '/v1/user/unlink',
        success: function (response) {
        	console.log(response)
        },
        fail: function (error) {
          console.log(error)
        },
      })
      Kakao.Auth.setAccessToken(undefined)
    }
  }  
</script> -->

{% endblock  %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<h1>비밀번호 변경</h1>


<form action="{% url 'accounts:password' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="비밀번호 변경" class="btn btn-primary">
</form>
    


{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<h1>profile</h1>

    <img src="#" alt="">
    <h2>{{ user.name }}님 안녕하세요!</h2>
    <p>팔로워</p>
    <p>팔로우</p>
    
    <p> 좋아요 한 글</p>



{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<body>
    <header>
        <h2>&nbsp;&nbsp;회원가입</h2>
    </header><br>

    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
            <div class="input-box">
              <input id="username" type="text" name="username" placeholder="아이디">
              <label for="username">&nbsp;&nbsp;아이디</label>
            </div>&nbsp;&nbsp;150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.
    
          <div class="input-box">
            <input id="password" type="password" name="password1" placeholder="비밀번호">
            <label for="password">&nbsp;&nbsp;비밀번호</label>
            </div>&nbsp;&nbsp;다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.<br>
            &nbsp;&nbsp;비밀번호는 최소 8자 이상이어야 합니다.<br>
            &nbsp;&nbsp;통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.<br>
            &nbsp;&nbsp;숫자로만 이루어진 비밀번호는 사용할 수 없습니다.
    
          <div class="input-box">
            <input id="password" type="password" name="password2" placeholder="비밀번호 확인">
            <label for="password">&nbsp;&nbsp;비밀번호 확인</label>
          </div>&nbsp;&nbsp;확인을 위해 이전과 동일한 비밀번호를 입력하세요.
    
          <div class="input-box">
            <input id="user.name" type="user.name" name="last_name" placeholder="이름">
            <label for="user.name">&nbsp;&nbsp;이름</label>
          </div>
    
          <div class="input-box">
            <input id="email" type="email" name="email" placeholder="이메일">
            <label for="email">&nbsp;&nbsp;이메일</label>
          </div>
    
        <input type="submit" value="회원가입" class="btn btn-primary">
    </form>
</body>

{% endblock  %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %}

<h1>정보 수정</h1>


<form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="수정하기" class="btn btn-primary">
    <a href="{% url 'accounts:password' %}" class="btn btn-warning">비밀번호변경</a>
    <a href="{% url 'accounts:delete' %}" class="btn btn-danger">계정 삭제</a>
</form>
    


{% endblock  %}